apiVersion: v1
kind: Service
metadata:
  name: golang-api-crud
spec:
  type: ClusterIP
  selector:
    app: golang-api-crud
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP