apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: golang-api-crud-dev

resources:
- ../../base
- namespace.yml
- service-external.yml

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: golang-api-crud
images:
- name: ghcr.io/alexsandroocanha/golang-api-crud
  newTag: 68ec805dac25bdfbd841b266d594a463635de864
