apiVersion: v1
kind: Service
metadata:
  name: golang-api-crud-external
spec:
  type: LoadBalancer
  selector:
    app: golang-api-crud
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP