apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-api-crud-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alexsandroocanha/Golang-Api-Crud-Manifests.git
    targetRevision: main
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: golang-api-crud-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-api-crud-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alexsandroocanha/Golang-Api-Crud-Manifests.git
    targetRevision: main
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: golang-api-crud-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m