apiVersion: v1
kind: Secret
metadata:
  name: golang-api-crud-db-credentials
  namespace: golang-api-crud
type: Opaque
stringData:
  DB_HOST: "CHANGE_ME"
  DB_PORT: "5432"
  DB_USER: "CHANGE_ME"
  DB_PASSWORD: "CHANGE_ME"
  DB_NAME: "CHANGE_ME"