apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - App/configmap.yml
  - App/deployment.yml
  - App/horizontal-altoscaler.yml
  - Cluster/pod-disruption-budget.yml
  - Cluster/service-account.yml
  - Cluster/service.yml
  - Policy/network-policy.yml

images:
  - name: ghcr.io/alexsandroocanha/golang-api-crud
    newTag: stable